package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "User")
   private com.User user;
   @org.kie.api.definition.type.Label(value = "Widget")
   private com.Widget widget;

   public FormData()
   {
   }

   public com.User getUser()
   {
      return this.user;
   }

   public void setUser(com.User user)
   {
      this.user = user;
   }

   public com.Widget getWidget()
   {
      return this.widget;
   }

   public void setWidget(com.Widget widget)
   {
      this.widget = widget;
   }

   public FormData(com.User user, com.Widget widget)
   {
      this.user = user;
      this.widget = widget;
   }

}