package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User")
   private com.User user;
   @org.kie.api.definition.type.Label("Widget")
   private com.Widget widget;

   @org.kie.api.definition.type.Label("Show Widget Details")
   private java.lang.Boolean showWidgetDetails;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;

   public FormData()
   {
   }

   public com.User getUser()
   {
      return this.user;
   }

   public void setUser(com.User user)
   {
      this.user = user;
   }

   public com.Widget getWidget()
   {
      return this.widget;
   }

   public void setWidget(com.Widget widget)
   {
      this.widget = widget;
   }

   public java.lang.Boolean getShowWidgetDetails()
   {
      return this.showWidgetDetails;
   }

   public void setShowWidgetDetails(java.lang.Boolean showWidgetDetails)
   {
      this.showWidgetDetails = showWidgetDetails;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public FormData(com.User user, com.Widget widget,
         java.lang.Boolean showWidgetDetails, java.lang.String name)
   {
      this.user = user;
      this.widget = widget;
      this.showWidgetDetails = showWidgetDetails;
      this.name = name;
   }

}