package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "State Code")
   private java.lang.String stateCode;

   public User()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStateCode()
   {
      return this.stateCode;
   }

   public void setStateCode(java.lang.String stateCode)
   {
      this.stateCode = stateCode;
   }

   public User(java.lang.String name, java.lang.String stateCode)
   {
      this.name = name;
      this.stateCode = stateCode;
   }

}