package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Widget implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Count")
   private java.lang.Integer count;
   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Year Built")
   private java.lang.Integer yearBuilt;

   public Widget()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getCount()
   {
      return this.count;
   }

   public void setCount(java.lang.Integer count)
   {
      this.count = count;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Integer getYearBuilt()
   {
      return this.yearBuilt;
   }

   public void setYearBuilt(java.lang.Integer yearBuilt)
   {
      this.yearBuilt = yearBuilt;
   }

   public Widget(java.lang.String name, java.lang.Integer count,
         java.lang.String description, java.lang.Integer yearBuilt)
   {
      this.name = name;
      this.count = count;
      this.description = description;
      this.yearBuilt = yearBuilt;
   }

}