import com.redhat.Assignment;
import com.redhat.FormEvent;

rule "Create assignment"
    agenda-group "assignment"
when 
    not Assignment ( )
then
    System.err.println("Creating assignment!");
    insert (new Assignment( ) );
end

rule "Dynamic assignment name one"
    agenda-group "assignment"
when
    FormEvent ( source == "one" )
    $assignment : Assignment ( name == null )
then
    System.err.println("Setting name to dev1");
    modify ($assignment) {
        setName (  "dev1" )
    }
end

rule "Dynamic assignment name two"
    agenda-group "assignment"
when
    FormEvent ( source == "two" )
    $assignment : Assignment ( name == null )
then
    System.err.println("Setting name to dev2");
    modify ($assignment) {
        setName (  "dev2" )
    }
end

rule "Dynamic assignment role"
    agenda-group "assignment"
when 
    FormEvent ( severity > 5 )
    $assignment : Assignment ( role == null )
then
    System.err.println("Setting role to reviewers");
    modify ($assignment) {
        setRole (  "reviewers" )
    }
end