package com.redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Assignment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String role;

   public Assignment()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getRole()
   {
      return this.role;
   }

   public void setRole(java.lang.String role)
   {
      this.role = role;
   }

   public Assignment(java.lang.String name, java.lang.String role)
   {
      this.name = name;
      this.role = role;
   }

}